/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package signing;

import org.junit.Ignore;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test @Ignore public void testAppHasAGreeting() {
        //todo: cleanup
    }
}
