version: 2

jobs:
  rust-verify:
    resource_class: large
    docker:
      - image: rust:1
    steps:
      - checkout
      - run: cd rust && cargo build -p verify-webhook
      - run: cd rust/verify && ../../.circleci/test-verify cargo run -q --

  python-verify:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: cd python && pipenv sync
      - run: cd python && ../.circleci/test-verify pipenv run python verify.py

  csharp-verify:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run: cd csharp/verify && dotnet restore
      - run: cd csharp/verify && ../../.circleci/test-verify dotnet run --

workflows:
  version: 2
  test:
    jobs:
      - rust-verify
      - python-verify
      - csharp-verify
