/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package signing;

import com.nimbusds.jose.JOSEException;
import picocli.CommandLine;

import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException, JOSEException {
        CommandLine commandLine = new CommandLine(new RequestSigner());

        if (args.length == 0) {
            commandLine.usage(System.out);
            return;
        }

        int exitCode = commandLine.execute(args);
        System.exit(exitCode);
    }
}
